### PR TITLE
DTSAM-388 add new case roles for Private Law

### PR DESCRIPTION
**Pull request by abul-syed**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSAM-388

### Change description ###

PRL case roles:

| Case role  | Assignee has role |
| ------------- | ------------- |
| allocated-ctsc-caseworker  | ctsc or ctsc-team-leader  |
| allocated-admin-caseworker  | hearing-centre-admin or hearing-centre-team-leader  |

### CODE REVIEW

**Review by mikebrownccd — DISMISSED** [review]
LGTM

**Review by mattnayler — DISMISSED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
Re-approved after config change.

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Pull request merged**
