### PR TITLE
AM-2954:  Create a new system role for Civil

### PR DESCRIPTION
**Pull request by prashanthkumarnb**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/AM-2954

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ *] No
```

### CODE REVIEW

**Review by mikebrownccd — DISMISSED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
Re-approved after minor change, 55f2491d028374fb0a60f9d81d01fc67010bed28, 34f0637399129337aab2d48c1bb3f74af602f0c3, 4ce792cf6ab8b4136b3f9b7f7b984f9e79077ecd.

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Pull request merged**
