### PR TITLE
DTSAM-288: Updated new case ids.

### PR DESCRIPTION
**Pull request by SivaKanukolluQA**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSAM-288

### Change description ###
Updated new case IDs.

**Does this PR introduce a breaking change?** (check one with "x")
[x] No

### CODE REVIEW

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by abul-syed — APPROVED** [review]
lgtm

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by abul-syed — APPROVED** [review]
lgtm

**Review by mattnayler — APPROVED** [review]

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
Re-apporved

**Pull request merged**
